server:
  port: 5050
spring:
  servlet:
    multipart:
      max-file-size: 1MB
      max-request-size: 1MB
  main:
    allow-circular-references: true
  jpa:
    show-sql: true
    generate-ddl: true
    hibernate.ddl-auto: update
    defer-datasource-initialization: true

  datasource:
    url: jdbc:mysql://localhost:3306/vet
    username: root
    password: SpringBoot!
    driver-class-name: com.mysql.cj.jdbc.Driver

  sql:
    init:
      mode: always

springdoc:
  swagger-ui:
    path: /docs.html

vet:
  app:
    jwtSecret: verySecretKey
    jwtExpirationMs: 86400000
